[package]
name = "gage_study"
version = "0.0.3"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
csv = "1.3.1"
log = "0.4.27"
