[package]
name = "gage_study"
version = "0.0.2"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
csv = "1.1.6"
thiserror = "1.0.38"
